In [1]:
import pandas as pd

df = pd.read_csv(r'Dataset/diabetes_risk_prediction_dataset.csv')

df.sample(10)

,Patient_ID,Age,Gender,Country,Height_cm,Weight_kg,BMI,Waist_Circumference_cm,Blood_Glucose,HbA1c,...,Fatty_Liver,PCOS,Medication_Adherence,Work_Type,Residence_Type,Daily_Water_Intake_L,Diabetes_Risk_Score,AI_Health_Recommendation,Doctor_Consultation_Needed,Diabetes_Risk
15392,15393,79.0,Other,Saudi Arabia,167.7,127.7,45.4,93.3,162.4,9.3,...,No,Yes,Poor,Business,Urban,2.4,96,Immediate Lifestyle Intervention,Yes,High
38369,38370,89.0,Other,China,147.6,54.8,25.2,105.2,135.9,10.9,...,Yes,No,Poor,Government,Urban,1.9,97,Begin Diabetes Management Plan,Yes,High
2338,2339,79.0,Male,Spain,171.1,78.4,26.8,133.6,104.5,8.2,...,Yes,No,Poor,Private,Rural,4.5,99,Begin Diabetes Management Plan,Yes,High
40949,40950,67.0,Other,China,153.8,82.6,34.9,95.9,95.5,6.5,...,No,Yes,Average,Student,Rural,4.1,80,Immediate Lifestyle Intervention,Yes,High
47119,47120,86.0,Female,South Africa,175.1,81.5,26.6,122.1,168.2,6.8,...,Yes,Yes,Poor,Government,Rural,2.9,88,Consult Endocrinologist Immediately,Yes,High
31082,31083,52.0,Male,Brazil,170.7,103.2,35.4,123.0,110.8,9.8,...,No,No,Average,Retired,Urban,2.4,81,Immediate Lifestyle Intervention,Yes,High
13895,13896,49.0,Other,Pakistan,185.9,104.5,30.2,98.5,92.6,11.7,...,Yes,No,Poor,Retired,Rural,1.9,54,Reduce Sugar Intake,Yes,Moderate
42900,42901,89.0,Female,Indonesia,179.1,56.9,17.7,131.4,154.9,12.0,...,Yes,No,Poor,Government,Rural,2.3,57,Healthy Diet Plan,Yes,Moderate
42504,42505,37.0,Other,Argentina,194.0,111.5,29.6,105.6,205.1,4.7,...,Yes,No,Good,Business,Urban,3.1,58,Monitor Blood Glucose,Yes,Moderate
39727,39728,90.0,Male,South Korea,156.2,114.0,46.7,84.8,206.8,5.3,...,Yes,No,Poor,Retired,Urban,1.3,78,Medical Evaluation Required,Yes,High

In [2]:
df.isna().sum()

Patient_ID                       0
Age                            497
Gender                           0
Country                          0
Height_cm                     2945
Weight_kg                     2962
BMI                              0
Waist_Circumference_cm           0
Blood_Glucose                  959
HbA1c                         1974
Fasting_Blood_Sugar              0
Insulin_Level                    0
Blood_Pressure_Systolic          0
Blood_Pressure_Diastolic         0
Total_Cholesterol             1000
HDL                           1000
LDL                           1000
Triglycerides                 1000
Heart_Rate                       0
Physical_Activity_Level        500
Exercise_Hours_Per_Week       1992
Daily_Walking_Minutes         1964
Diet_Quality                     0
Sugar_Intake_Level               0
Sleep_Hours                   2017
Stress_Level                     0
Smoking_Status                   0
Alcohol_Consumption              0
Family_History_Diabetes          0
Hypertension                     0
Heart_Disease                    0
Fatty_Liver                      0
PCOS                             0
Medication_Adherence          1000
Work_Type                        0
Residence_Type                   0
Daily_Water_Intake_L             0
Diabetes_Risk_Score              0
AI_Health_Recommendation         0
Doctor_Consultation_Needed       0
Diabetes_Risk                    0
dtype: int64

In [3]:
df.shape

(50000, 41)

In [4]:
df.ffill(inplace=True)
df.sample(10)

,Patient_ID,Age,Gender,Country,Height_cm,Weight_kg,BMI,Waist_Circumference_cm,Blood_Glucose,HbA1c,...,Fatty_Liver,PCOS,Medication_Adherence,Work_Type,Residence_Type,Daily_Water_Intake_L,Diabetes_Risk_Score,AI_Health_Recommendation,Doctor_Consultation_Needed,Diabetes_Risk
35668,35669,41.0,Female,United Kingdom,167.8,115.1,40.9,80.3,192.8,10.6,...,Yes,Yes,Good,Retired,Urban,1.4,77,Strict Blood Sugar Monitoring,Yes,High
36597,36598,57.0,Other,Mexico,155.3,127.5,52.9,110.3,171.6,10.4,...,Yes,Yes,Average,Government,Urban,2.4,89,Immediate Lifestyle Intervention,Yes,High
48305,48306,86.0,Male,Australia,154.0,127.9,53.9,116.5,157.0,9.1,...,No,Yes,Poor,Government,Urban,4.9,100,Immediate Lifestyle Intervention,Yes,High
26263,26264,67.0,Male,Malaysia,146.1,108.1,39.6,115.2,228.4,6.2,...,Yes,No,Good,Business,Rural,4.4,78,Begin Diabetes Management Plan,Yes,High
13297,13298,82.0,Female,Germany,185.5,123.2,35.8,77.0,239.2,6.9,...,No,Yes,Average,Retired,Urban,3.4,73,Strict Blood Sugar Monitoring,Yes,High
18701,18702,34.0,Male,India,160.4,65.6,25.5,67.2,83.0,9.5,...,No,Yes,Good,Student,Rural,1.7,61,Reduce Sugar Intake,Yes,Moderate
33382,33383,28.0,Female,Canada,182.6,62.7,18.8,88.2,247.0,8.8,...,Yes,No,Good,Student,Urban,1.4,67,Begin Diabetes Management Plan,Yes,High
12645,12646,50.0,Other,France,145.3,71.0,33.6,118.6,194.2,8.9,...,Yes,Yes,Good,Private,Urban,3.3,100,Strict Blood Sugar Monitoring,Yes,High
7368,7369,33.0,Male,Pakistan,151.6,120.7,52.5,119.7,197.7,9.3,...,Yes,Yes,Good,Business,Urban,3.7,65,Medical Evaluation Required,Yes,High
34115,34116,33.0,Male,Russia,158.8,117.2,46.5,66.7,163.6,9.4,...,No,Yes,Average,Private,Rural,1.6,84,Medical Evaluation Required,Yes,High

In [5]:
df.isna().sum()

Patient_ID                    0
Age                           0
Gender                        0
Country                       0
Height_cm                     0
Weight_kg                     0
BMI                           0
Waist_Circumference_cm        0
Blood_Glucose                 0
HbA1c                         0
Fasting_Blood_Sugar           0
Insulin_Level                 0
Blood_Pressure_Systolic       0
Blood_Pressure_Diastolic      0
Total_Cholesterol             0
HDL                           0
LDL                           0
Triglycerides                 0
Heart_Rate                    0
Physical_Activity_Level       0
Exercise_Hours_Per_Week       0
Daily_Walking_Minutes         0
Diet_Quality                  0
Sugar_Intake_Level            0
Sleep_Hours                   0
Stress_Level                  0
Smoking_Status                0
Alcohol_Consumption           0
Family_History_Diabetes       0
Hypertension                  0
Heart_Disease                 0
Fatty_Liver                   0
PCOS                          0
Medication_Adherence          0
Work_Type                     0
Residence_Type                0
Daily_Water_Intake_L          0
Diabetes_Risk_Score           0
AI_Health_Recommendation      0
Doctor_Consultation_Needed    0
Diabetes_Risk                 0
dtype: int64

In [6]:
df.drop_duplicates(inplace=True)

In [7]:
df.dtypes

Patient_ID                      int64
Age                           float64
Gender                            str
Country                           str
Height_cm                     float64
Weight_kg                     float64
BMI                           float64
Waist_Circumference_cm        float64
Blood_Glucose                 float64
HbA1c                         float64
Fasting_Blood_Sugar           float64
Insulin_Level                 float64
Blood_Pressure_Systolic         int64
Blood_Pressure_Diastolic        int64
Total_Cholesterol             float64
HDL                           float64
LDL                           float64
Triglycerides                 float64
Heart_Rate                      int64
Physical_Activity_Level           str
Exercise_Hours_Per_Week       float64
Daily_Walking_Minutes         float64
Diet_Quality                      str
Sugar_Intake_Level                str
Sleep_Hours                   float64
Stress_Level                      str
Smoking_Status                    str
Alcohol_Consumption               str
Family_History_Diabetes           str
Hypertension                      str
Heart_Disease                     str
Fatty_Liver                       str
PCOS                              str
Medication_Adherence              str
Work_Type                         str
Residence_Type                    str
Daily_Water_Intake_L          float64
Diabetes_Risk_Score             int64
AI_Health_Recommendation          str
Doctor_Consultation_Needed        str
Diabetes_Risk                     str
dtype: object

In [8]:
df[['Family_History_Diabetes',
    'Hypertension',
    'Heart_Disease',
    'Fatty_Liver',
    'PCOS',
    'Doctor_Consultation_Needed']]

,Family_History_Diabetes,Hypertension,Heart_Disease,Fatty_Liver,PCOS,Doctor_Consultation_Needed
0,Yes,No,Yes,Yes,No,Yes
1,Yes,No,Yes,Yes,Yes,Yes
2,Yes,No,No,Yes,No,Yes
3,Yes,Yes,No,No,No,Yes
4,No,Yes,Yes,Yes,Yes,Yes
...,...,...,...,...,...,...
49995,Yes,No,No,No,Yes,Yes
49996,No,No,Yes,Yes,No,No
49997,Yes,Yes,No,Yes,Yes,Yes
49998,No,No,No,Yes,Yes,No
49999,No,Yes,No,Yes,Yes,Yes

In [9]:
mappings = {'Yes':True, 'No':False}
df['Family_History_Diabetes'] = df['Family_History_Diabetes'].map(mappings)
df['Hypertension'] = df['Hypertension'].map(mappings)
df['Heart_Disease'] = df['Heart_Disease'].map(mappings)
df['Fatty_Liver'] = df['Fatty_Liver'].map(mappings)
df['PCOS'] = df['PCOS'].map(mappings)
df['Doctor_Consultation_Needed'] = df['Doctor_Consultation_Needed'].map(mappings)

In [10]:
df[['Physical_Activity_Level',
    'Diet_Quality',
    'Sugar_Intake_Level',
    'Stress_Level',
    'Alcohol_Consumption',
    'Medication_Adherence',
    'Diabetes_Risk']].value_counts()

Physical_Activity_Level  Diet_Quality  Sugar_Intake_Level  Stress_Level  Alcohol_Consumption  Medication_Adherence  Diabetes_Risk
Low                      Poor          Low                 Moderate      Frequently           Poor                  High             81
                                       Moderate            High          Frequently           Poor                  High             79
                         Average       Low                 Moderate      Frequently           Poor                  High             76
                         Poor          High                High          Frequently           Good                  High             75
                         Healthy       High                High          Occasionally         Average               High             75
                                                                                                                                     ..
High                     Average       Moderate            High          Occasionally         Poor                  Low               1
                                                                         Never                Good                  Low               1
Moderate                 Healthy       High                High          Occasionally         Good                  Low               1
                         Average       High                Moderate      Occasionally         Average               Low               1
                         Poor          Low                 Low           Occasionally         Good                  Low               1
Name: count, Length: 1749, dtype: int64

In [11]:
df['Diabetes_Risk'].value_counts()

Diabetes_Risk
High        36593
Moderate    12937
Low           470
Name: count, dtype: int64

In [14]:
df = df.sample(n=10000,random_state=42)
df

,Patient_ID,Age,Gender,Country,Height_cm,Weight_kg,BMI,Waist_Circumference_cm,Blood_Glucose,HbA1c,...,Fatty_Liver,PCOS,Medication_Adherence,Work_Type,Residence_Type,Daily_Water_Intake_L,Diabetes_Risk_Score,AI_Health_Recommendation,Doctor_Consultation_Needed,Diabetes_Risk
25056,25057,46.0,Other,South Africa,192.1,78.1,21.2,80.5,238.5,11.9,...,True,False,Average,Private,Rural,4.4,97,Begin Diabetes Management Plan,True,High
30334,30335,58.0,Other,Australia,184.2,85.5,25.2,63.7,182.9,7.8,...,False,True,Average,Retired,Rural,2.7,93,Immediate Lifestyle Intervention,True,High
17962,17963,46.0,Male,India,153.7,45.5,19.3,73.9,225.3,9.5,...,False,False,Average,Business,Urban,4.2,86,Begin Diabetes Management Plan,True,High
39588,39589,83.0,Male,Nigeria,153.8,79.2,33.5,127.1,185.1,11.8,...,False,False,Average,Private,Urban,2.4,78,Begin Diabetes Management Plan,True,High
34107,34108,77.0,Other,Spain,185.9,124.3,36.0,113.7,195.7,5.8,...,True,True,Good,Business,Urban,3.7,62,Healthy Diet Plan,True,Moderate
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49939,49940,85.0,Other,Egypt,149.6,64.4,28.8,73.7,92.4,9.5,...,True,False,Average,Private,Rural,2.8,90,Strict Blood Sugar Monitoring,True,High
6420,6421,31.0,Male,United States,163.8,107.8,40.2,97.7,152.8,9.6,...,False,False,Good,Student,Urban,2.2,81,Immediate Lifestyle Intervention,True,High
48421,48422,46.0,Other,Spain,188.5,123.6,34.8,104.5,227.8,6.6,...,False,True,Poor,Business,Rural,1.0,92,Immediate Lifestyle Intervention,True,High
26037,26038,43.0,Female,India,184.9,108.5,31.7,78.7,110.8,7.3,...,False,True,Average,Private,Rural,4.5,75,Immediate Lifestyle Intervention,True,High
31247,31248,44.0,Female,United States,181.3,102.5,31.2,107.4,94.3,4.9,...,False,False,Poor,Private,Urban,2.0,69,Begin Diabetes Management Plan,True,High

In [15]:
df.to_csv('Dataset/Cleaned_dataset.csv')